name: AML Mod Compiler

on:
  workflow_dispatch:
    inputs:
      mod_name:
        description: 'اسم المود الذي تريد بناءه'
        required: true
        default: 'MyCustomMod'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository...
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Download GTA:SA structures zip...
      uses: wei/wget@v1
      with:
        args: -O ./structs.zip https://github.com/RusJJ/GTASAAndroid_Structs/archive/refs/heads/main.zip

    - name: Extract and organize structures...
      run: |
        unzip -q ./structs.zip
        mkdir -p ./jni
        mv ./GTASAAndroid_Structs-main/* ./jni/
        rm -rf ./structs.zip ./GTASAAndroid_Structs-main

    - name: Install Android NDK (r24)...
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r24
        local-cache: true

    - name: Build the code...
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./jni/Android.mk NDK_APPLICATION_MK=./jni/Application.mk NDK_DEBUG=0 -j5

    - name: Upload the mod!
      uses: actions/upload-artifact@v4
      with:
        name: compiled-mod-${{ github.event.inputs.mod_name }}
        path: ./libs
